name: Deployment

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 14
      uses: actions/setup-node@v4
      with:
        node-version: 14
    - name: Install, test, deploy
      run: |
        yarn install --frozen-lockfile
        yarn test
        sh deploy.sh
      env:
        CAPROVER_PASSWORD: ${{ secrets.CAPROVER_PASSWORD }}
        CAPROVER_MACHINE_01: ${{ secrets.CAPROVER_MACHINE_01 }}
        CAPROVER_MACHINE_02: ${{ secrets.CAPROVER_MACHINE_02 }}
        CI: true